### ISSUE TITLE
Automaton's animations

### ISSUE THREAD

**Issue by xllifi** [kyber-6/mythicmobs#11]
### Describe the bug

"attack" animation is cancelled too soon. Watch the [video demonstration](https://cdn.discordapp.com/attachments/942314876779511858/1131142712180080740/Desktop_2023.07.19_-_18.34.16.14.mp4)

### Reproduction steps

Let automaton attack any mob

### Mod version

1.3.0

### Minecraft version

1.20.1

**Comment by xllifi** [comment]
Also when automaton is walking and attacking its legs stop moving

**Comment by thrasos-dev** [comment]
I will be reworking Automatons in general. This includes their attacks, animation queues, and how they will spawn.
