### ISSUE TITLE
Too many Automatons spawning

### ISSUE THREAD

**Issue by Arkiln** [kyber-6/mythicmobs#12]
### Describe the bug

Too many of the Bronze golems are spawning in a village I created, it seems like there's no limit to how many there are.

### Reproduction steps

Create a an artificial village / trading post, golems will constantly spawn in the area.

### Screenshots

![image](https://github.com/kyber-6/mythicmobs/assets/1668122/cb35d68f-fa6f-43e4-a411-a57c47f9b878)

### Mod version

1.3.0

### Minecraft version

1.19.2

**Comment by x0tempus0x** [comment]
I second that. Same happened in my 1.20.1 world in normal villages and even in my base (house). Had to disable the automatons. Now after updating to 0.7.0  I re-enable it and watch what happens.

**Comment by innercrayon** [comment]
+1

**Comment by thrasos-dev** [comment]
I will be re-working the Automatons in the near future.

**Comment by JordanKef** [comment]
+1 for me, made my village almost 6 times bigger, my villagers count to 20 and the automantos up to 60. My ram cannot handle it, i destroyed half of my village

**Comment by thrasos-dev** [comment]
This issue has been solved in the latest version. Automatons no longer spawn, you have to craft them.

**Comment by JordanKef** [comment]
i play on curseforge, maybe it is not updated in the modpack, i will change version and try again
