### ISSUE TITLE
Drake's sounds are in stereo instead of mono

### ISSUE THREAD

**Issue by NordAct** [kyber-6/mythicmobs#17]
### Describe the bug

Drake sounds use stereo format instead of mono, which results in Minecraft not applying distance effects on the sound (sound will not fade with distance, resulting you in hearing the sound from very far away from the entity)

### Reproduction steps

1. Find drake
2. Get it within your render distance
3. Enjoy its roars like it's right next to you despite it being several dozens blocks away

### Mod version

1.3.5

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
Fixed in v1.3.6.
