### ISSUE TITLE
incompatible with guardvillagers

### ISSUE THREAD

**Issue by WorldsOfRosefire** [kyber-6/mythicmobs#18]
### Describe the bug

it prevents guards from spawning in villages.
mythicmobs 1.3.6
guardvillagers 2.0.7

### Reproduction steps

adding mythicmobs to guardvillagers and find some villages, removing mythicmobs and find another one.

### Mod version

mythicmobs 1.3.6

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
Please report this to Guard Villagers as well.
