### ISSUE TITLE
Guard Villagers become invisible when used with Mythic Mobs

### ISSUE THREAD

**Issue by CasualJeremy** [kyber-6/mythicmobs#2]
### Describe the bug

Guard Villagers still spawn but are invisible when used with Mythic Mobs.

### Reproduction steps

Installed both mods, the Guard Villagers were invisible. Removed MythicMobs and they guards reappeared.

### Mod version

1.19.2

**Comment by Sunconure11** [comment]
@MrSterner

**Comment by Sunconure11** [comment]
Did some digging myself. Wasn't able to recreate on a clean instance. Can you post more info for @kyber-6, such as what other mods you have, logs, etc?
