### ISSUE TITLE
[Bug] Continuation of #17 - (Stereo instead of mono sounds)

### ISSUE THREAD

**Issue by EnderGirl1500** [kyber-6/mythicmobs#20]
### Describe the bug

I was about to post the same thing as #17 now. I downloaded the mod yesterday and I got the bugs I used to with another mod because of the stereo sounds.

[Detailed explanation]

In _[Let's Do] Beachparty_ mod, pelicans used to be heard at the same volume while close to them. When _Physics Sounds_ was enabled, it was a complete disaster: I heard pelicans ALWAYS as if they were in the same coordinates as me, and I had to move like 5 chunks away from them to stop their sounds.

I contacted the _Physics Sounds_ mod's dev, thinking it was their fault, and they told me it was because those pelicans had stereo sounds instead of mono.

Now I hear drakes the same way as I did with pelicans. I thought it might be the same issue, but if you said it has been fixed, I don't know what happens anymore.

### Reproduction steps

1. Install both this mod and Physics Sounds
2. Open new world
3. Spawn / Find drakes
4. You'll hear them even if far away

### Mod version

Latest

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
Fixed!
