### ISSUE TITLE
One of the Drake's roars is playing globally rather than positionally

### ISSUE THREAD

**Issue by TheSpiderDungeon** [kyber-6/mythicmobs#22]
### Describe the bug

One of the Drake's roars is playing globally rather than positionally. When a Drake is rendered, one of its roars plays globally at full volume rather than at the mob's position where the sound can drop off.

### Reproduction steps

(The reproduction steps section is mostly irrelevant.)

### Mod version

1.3.9

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
Fixed!
