### ISSUE TITLE
mob spawns don't seem right

### ISSUE THREAD

**Issue by GrogusFF** [kyber-6/mythicmobs#25]
### Describe the bug

every mob in the mod seems to spawn pretty much anywhere. the only exceptions i've noticed are the automaton and chupacabra, which i believe are both correct.

drakes, sporelings, and kobolds however, i've seen spawn in every biome. it doesn't really make sense for sporelings to be spawning in places you can't find an abundance of mushrooms, like badlands and snowy slopes, where i've seen them spawn.

and drakes and kobolds i can only imagine spawning in savanna biomes or underground, but yet i see them spawn regularly in beaches and frozen lakes.

### Reproduction steps

load game with the mod

### Mod version

1.4.0

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
Spawn system has been enhanced in the rewrite, please test and feel free to provide feedback.
