### ISSUE TITLE
game crash when shift clicking item from hotbar into inv while on mount

### ISSUE THREAD

**Issue by shebaaa** [kyber-6/mythicmobs#27]
### Describe the bug

when i shift click any item from my hotbar to move it into my inventory quickly while im on a mount, it just crashes my game. it doesn't matter which mount i'm on, it just crashes. 

### Reproduction steps

sit on mount
open inventory
shift click item on hotbar
game crashes

### Mod version

1-7.4

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
What mount?

**Comment by tuskrus799** [comment]
This is also happening for other players on my server, the mount was the Zar-ptak

**Comment by thrasos-dev** [comment]
You've got the wrong mod, this is Mythic Mobs, not Mythic Mounts.
