### ISSUE TITLE
tamed drake dont changing custom health

### ISSUE THREAD

**Issue by joaovfsilva** [kyber-6/mythicmobs#29]
### Describe the bug

i want to play with stronger pets so i changed drake's life and damage at config, but when i tame them they come back to normal stats. 

### Reproduction steps

changed drake's life and damage and tamed them

### Mod version

fabric 1.4.5

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
Please test if the issue persists in the rewrite.
