### ISSUE TITLE
[SUGGESTION] Allow automata to be made from bronze from any mod that is tagged properly, as well as repaired with such

### ISSUE THREAD

**Issue by Sunconure11** [kyber-6/mythicmobs#3]
### Describe your suggestion

Several mods add bronze on their own. It'd be best to allow some compat with such.

**Comment by thrasos-dev** [comment]
Can you point me to some mods which add such compatibility so I can see how they do it?

**Comment by Sunconure11** [comment]
https://www.curseforge.com/minecraft/mc-mods/mythicmetals

**Comment by whatamaniac** [comment]
Or You can also try Brass ingots>Brass Blocks>then construct the golem like vanilla... From Create Mod as it matches the color and a lil bit of Steampunk theme... https://create.fandom.com/wiki/Brass_Ingot

**Comment by Sunconure11** [comment]
I think the dev should allow anything tagged/oredict'd as brass to repair, as not everyone has the same mod sets.

**Comment by milkev** [comment]
To provide compatability with other mods bronze ingots;
First you get the c tag in a class:
![image](https://github.com/kyber-6/mythicmobs/assets/22010128/02e5be07-74d9-4fa6-834e-6010c8fcd0a4)
Then you can check if an item is in the tag like this:
![image](https://github.com/kyber-6/mythicmobs/assets/22010128/7480a563-ddc7-4005-b1ce-b56990c95b3a)

you would also have to add your bronze ingot to c/items/bronze_ingots.json as well [Heres the fabric wiki regarding tags](https://fabricmc.net/wiki/tutorial:tags)

**Comment by thrasos-dev** [comment]
@milkev 

Thank you for this, I am working on an update now to implement everything with tags.

I have also defined `TagKey<Block> BRONZE_BLOCKS` for creating the Automatons.

Can you help me out for making it so their pattern also checks for tag of `BRONZE_BLOCKS` instead of the `BRONZE_BLOCK` I registered in my mod?
```java
this.automatonPattern = BlockPatternBuilder.start().aisle("~^~", "###", "~#~")
                    .where('^', CachedBlockPosition.matchesBlockState(IS_GOLEM_HEAD_PREDICATE))
                    .where('#', CachedBlockPosition.matchesBlockState(BlockStatePredicate.forBlock(BlockRegistry.BRONZE_BLOCK)))
                    .where('~', pos -> pos.getBlockState().isAir()).build();
```

**Comment by thrasos-dev** [comment]
Resolved in the rewrite.

**Comment by milkev** [comment]
sorry, missed the email before. glad you got it figured out

**Comment by Lumb3rSamur4i** [comment]
https://modrinth.com/mod/bronze

i think this one is the most used
