### ISSUE TITLE
[1.20.1] Crash on load

### ISSUE THREAD

**Issue by Reshy** [kyber-6/mythicmobs#30]
### Describe the bug

Mod's causing crashes in a modpack environment.

### Reproduction steps

Unknown, investigating.

### Logs & crash-reports

https://pastebin.com/YBE0GPH7

### Mod version

mythicmobs-1.20.1-connector-1.4.5.jar

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
The version you are using is made possible through Sinytra Connector, which is experimental and not meant to be used in modpacks. An official Forge port will be coming soon.
