### ISSUE TITLE
[1.20.1] 0 Kobold spawn weight results in whole groups of warriors

### ISSUE THREAD

**Issue by twenty41** [kyber-6/mythicmobs#33]
### Describe the bug

This may just be an artifact of Minecraft's spawning systems, but I want to use this mod for _very rare_ exotic mobs to be found in the wild. Verryyy rare. I don't think the standard Kobold really fit my modpack, I just wanted the occasional Kobold warrior roaming about. But turning the regular Kobold to zero results in large groups

### Reproduction steps

Turn Kobold weight to zero

### Screenshots

![image](https://github.com/kyber-6/mythicmobs-mod/assets/46447750/664a9eb6-08e4-4c54-83e1-3dbfa8ce4329)

### Mod version

mythicmobs-1.20.1-fabric-1.4.5.jar

### Minecraft version

1.20.1 fabric

**Comment by thrasos-dev** [comment]
That does not have anything to do with it. The size for the spawn group of every mob is chosen randomly between a certain interval, you just happened to get large groups each time. I'll make a note to lower the group sizes.
