### ISSUE TITLE
Execution is not possible due to an error in the mode at the 'main' entry point stage.

### ISSUE THREAD

**Issue by Rosenkreuzer** [kyber-6/mythicmobs#35]
### Describe the bug

After installing this mod, a crashing error occurred while running Minecraft.

The shutdown crash description was: The game crashed whilst initializing game
Error: net.minecraftforge.fml.loading.EarlyLoadingException: Could not execute entrypoint stage 'main' due to errors, provided by 'mythicmobs'!

I am attaching the crash report.

### Reproduction steps

1. Run Minecraft.

2. A forced termination occurs after the loading bootstrap resource step.
(There were probably no conflicts with any other mods! Only mythicmobs was causing the error in the output log!)

### Logs & crash-reports

[crash-2023-12-19_03.29.32-client.txt](https://github.com/kyber-6/mythicmobs-mod/files/13707357/crash-2023-12-19_03.29.32-client.txt)

### Mod version

1.4.5

### Minecraft version

1.20.1

**Comment by Rosenkreuzer** [comment]
P.s. I am using a translator, so there may be awkward grammar.

**Comment by BlueKio** [comment]
Just had this issue too. The problem seems to be that it still requires Archaeology API as a dependency, however that only supports up to 1.19.2 -> 1.20, not 1.20.1. So it crashed without it, but you also get a version error with it. Hopefully it gets fixed soon, it's a great mod ^^

**Comment by thrasos-dev** [comment]
This mod was written for the Fabric mod loader. The Forge version of this mod is made possible through [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector), an experimental mod that allows Fabric mods to run on the Forge mod loader. Sinytra Connector is not yet ready to be used in heavily modded environments, so please do not report issues regarding the Forge version of Mythic Mobs. An "actual" Forge port is currently in the works, stay tuned.
