### ISSUE TITLE
game crashed in my modpack forge

### ISSUE THREAD

**Issue by Thunderrock424242** [kyber-6/mythicmobs#38]
### Describe the bug

when i launch my modpack it crashes

### Reproduction steps

luanch my modpack

### Logs & crash-reports

[latest.log](https://github.com/kyber-6/mythicmobs-mod/files/13780213/latest.log)

### Mod version

1.4.5

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
This mod was written for the Fabric mod loader. The Forge version of this mod is made possible through [Sinytra Connector](https://www.curseforge.com/minecraft/mc-mods/sinytra-connector), an experimental mod that allows Fabric mods to run on the Forge mod loader. Sinytra Connector is not yet ready to be used in heavily modded environments, so please do not report issues regarding the Forge version of Mythic Mobs. An "actual" Forge port is currently in the works, stay tuned.
