### ISSUE TITLE
Bronze Blocks (and cut variant) do not drop when broken

### ISSUE THREAD

**Issue by shinji257** [kyber-6/mythicmobs#39]
### Describe the bug

When attempting to break a bronze block with a pickaxe the item doesn't drop.  It will work on breaking for a long time (like it isn't recognized as a valid tool) then eventually disappears without a drop.

### Reproduction steps

Place bronze block and attempt to break with a pickaxe

### Mod version

1.4.5 Fabric

### Minecraft version

1.20.1

**Comment by thrasos-dev** [comment]
Fixed in the rewrite.
