### ISSUE TITLE
Kobolds are spawning in places they shouldn't.

### ISSUE THREAD

**Issue by Sunconure11** [kyber-6/mythicmobs#4]
### Describe the bug

I am finding kobolds in a world where they shouldn't spawn. The world in question is a dimension created by a datapack that is meant to be mostly bare.

### Reproduction steps

Go to a biome or world where they shouldn't normally spawn

### Screenshots

![image](https://github.com/kyber-6/mythicmobs/assets/5614902/48a01331-635a-4896-9e48-f9f79901c8ef)

### Mod version

1.1

**Comment by Sunconure11** [comment]
This issue is also applying to another mod you made, Useless Creature. @kyber-6

**Comment by thrasos-dev** [comment]
Solved in v1.2.
