### ISSUE TITLE
Kobold Warrior nerf 1.21, Kobold Spawn less in non jungle areas.

### ISSUE THREAD

**Issue by makumaku1974** [kyber-6/mythicmobs#44]
### Describe your suggestion

I think this is a bug and a feature request on the side and that feature request would be lower durability given towards Kobold spear, entity interaction should be implemented since it's a spear, and finally reducing the amount of emeralds drop and kobold spear drops for anti-farming.

### Benefits of the feature

Anti-Farm, Making the Kobold Warrior a much of a threat considering it's a spear by extending their interaction reach, and Make them only spawn in jungles for now. Biomes o Plenty kind of ruins the immersion with their existence at the moment.

Biome's O Plenty disperses them in any other areas that seem to be Kobold's shouldn't be spawning out of nowhere. Also
Making Kobold's and Kobold Warriors spawn more frequently on jungles. Kobold Warrior don't spawn in non jungle areas and Kobold only can spawn in non jungles by 1 or 2 entities.

**Comment by samuel-odinware** [comment]
I agree with the spear reach and drop rate. One of the things I love about the kobolds is the chance to get my weapon taken away; it makes the battle feel more engaging. Having multiple of spears in my inventory, from a few kills, takes away from that sense of peril.

**Comment by thrasos-dev** [comment]
Done in 14f2da4

**Comment by makumaku1974** [comment]
holy W. I'll be back playing MC since i've been busy playing Stalker.
