### ISSUE TITLE
Chupacabla config to disable it killing animals

### ISSUE THREAD

**Issue by Jszp03** [kyber-6/mythicmobs#45]
### Describe your suggestion

Please make a config to disable chupacabra killing / attacking animals. its bugged, it spawns in lit enviroment, it climbs / buggs out of fences etc and kills animals on farm

### Benefits of the feature

obvious

**Comment by thrasos-dev** [comment]
It’s not bugged, that’s the intended behaviour of the Chupacabra. I added a spawn weight config option to limit how much they spawn.
