### ISSUE TITLE
I think Kobold tried to get an item from me but i had no items

### ISSUE THREAD

**Issue by CaoTrongThang** [kyber-6/mythicmobs#48]
### Confirm mod version

No, I am not using version 1.21

### Describe the bug

Kobold tried to get an item from me but i had no items, so I got a "null" and crashed

### Reproduction steps

I was punching trees and a Kobold with an Axe (from [Improved Mobs make mobs can equip items](https://modrinth.com/mod/improved-mobs)) came and one-shot me, I died and crashed right after.

So in steps it'll look like: Kobold killed me first -> I died and dropped all the items in the[ Gravestone mod](https://modrinth.com/mod/pneumono_gravestones) -> Kobold tried to steal items > But there were no items > Crashed.

### Screenshots

I got no screenshots, but I do have logs and crash reports

### Logs & crash-reports

Fabric: 0.16.7
Minecraft version: 1.20.1
Logs: https://mclo.gs/xKDGYrH
Crash report: [crash-2024-10-29_01.16.22-server.txt](https://github.com/user-attachments/files/17547191/crash-2024-10-29_01.16.22-server.txt)

### Mod version

2.0.3

**Comment by thrasos-dev** [comment]
I am no longer supporting 1.20.1.

**Comment by CaoTrongThang** [comment]
Really hope you can fix this, i see you just updated for 1.20.1 and many people downloaded it.
