### ISSUE TITLE
Killing Kobolds with Looting-enhanced weapons cause duplication glitch

### ISSUE THREAD

**Issue by e314** [kyber-6/mythicmobs#49]
### Confirm mod version

Yes, I am using version 1.21

### Describe the bug

Items stolen by kobolds might be duplicated when killing the kobold with a Looting enchanted item.
This includes shulker boxes (or other containers) with their content, therefore breaking the whole game economy.

### Reproduction steps

1. Equip item you want duplicated in hand.
2. Get a kobold to steal it.
3. Hunt and kill that kobold with a weapon with Looting.
4. Repeat until you get 2 of that item.
5. If the duplicated was a container, add another item inside before withdrawing anything (Otherwise, contents stay "linked")

### Mod version

2.0.4 (In the Medival MC modpack)

**Comment by thrasos-dev** [comment]
This was fixed in 2.0.5, please update your mod.
