### ISSUE TITLE
Nerf kobold spear drop rate

### ISSUE THREAD

**Issue by Slooshix** [kyber-6/mythicmobs#51]
### Describe your suggestion

It seems that for every kobold warrier I kill, they drop a kobold spear. The kobold spear is such an incredible weapon, the attack swings twice as fast as an axe, and in the same amount it takes to swing an axe, deals 4 hearts more than an unenchanted diamond axe. Because of this, mobs are unable to reach you and they will die quickly. It does come with one downside, that being how it disables the ability to hold something in your off hand (e.g. shield/totem), but since it has a fast attack speed, this only barely balances it out. Due to this, I believe the kobold spear should be a rarer drop, maybe not trident rare, but the trident serves an example at how it should be further valued. I have adopted this as my main weapon and I believe it would be appropriate for it to be a rarer drop and not be something I can easily collect a lot of.

### Benefits of the feature

Decreasing the drop rate of the kobold spear would make it more valuable and balance out its usefulness.

**Comment by thrasos-dev** [comment]
Lowered drop rate in b2ac78f
