### ISSUE TITLE
capybaras spawn in mushroom island

### ISSUE THREAD

**Issue by inikishev** [kyber-6/mythicmobs#7]
### Describe the bug

![image](https://github.com/kyber-6/mythicmobs/assets/76593873/2c129528-dda3-404b-a399-25b32b0ec2c2)

### Reproduction steps

go to mashrum islands

### Screenshots

i killed them and new ones spawned 
![image](https://github.com/kyber-6/mythicmobs/assets/76593873/911a1beb-e283-48ab-a9ca-cb6eddf3e33f)

### Logs & crash-reports

stupid capybaras keep spawmcamping me
### Mod version

1.3.0

**Comment by thrasos-dev** [comment]
Chupacabras are meant to spawn in all Overworld biomes. You can adjust the spawn-rate in the config though.

**Comment by inikishev** [comment]
> Chupacabras are meant to spawn in all Overworld biomes. You can adjust the spawn-rate in the config though.

but the point of mushroom islands is that no mobs spawn in them https://minecraft.fandom.com/wiki/Mushroom_Fields

**Comment by thrasos-dev** [comment]
Resolved in the rewrite, now only Sporeling spawn in the Mushroom Fields.
